# site settings
title: Azevedo Lab
subtitle: University of Houston
email: razevedo@uh.edu
description: Theoretical evolutionary genetics
remote_theme: andrewbanchich/forty-jekyll-theme

# contact
twitter_url: https://twitter.com/rbazev
github_url: https://github.com/rbazev
street_address: <a href="http://www.uh.edu/nsm/biology-biochemistry/">Department of Biology & Biochemistry</a> <br /> University of Houston
state: Texas
zip_code: 77204-5001
country: United States of America
phone: (713) 743-4149

# build settings
markdown: kramdown
