title: Azevedo Lab
subtitle: University of Houston
email: razevedo@uh.edu
remote_theme: andrewbanchich/forty-jekyll-theme

# contact
twitter_url: https://twitter.com/rbazev

# build settings
markdown: kramdown
